from enum import Enum


class VertexIdEncoding(Enum):
    VERTEX_ID_ENCODING_IS_BASE_A_SHIFT = 7
    VERTEX_ID_ENCODING_SIN_SIGN_SHIFT = 6
    VERTEX_ID_ENCODING_COS_SIGN_SHIFT = 5
    VERTEX_ID_ENCODING_IS_SIN_LESSER_SHIFT = 4
    VERTEX_ID_ENCODING_VALUE_MASK = 15
